import { FunctionComponent, PropsWithChildren } from 'react'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface LayoutProps extends PropsWithChildren {}

const Layout: FunctionComponent<LayoutProps> = ({ children }) => {
  return (
    <>
      <main className="bg-slate-400/50">
        <div className="m-auto min-h-main max-w-[460px] bg-white md:max-w-[900px]">
          {children}
        </div>
      </main>
    </>
  )
}

export default Layout
