import { FunctionComponent, PropsWithChildren } from 'react'
import type { Metadata } from 'next'
import { HomeHeader } from '@/containers/layout/home/header/HomeHeader'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface LayoutProps extends PropsWithChildren {}

const Layout: FunctionComponent<LayoutProps> = ({ children }) => {
  return (
    <>
      <HomeHeader />
      <main>{children}</main>
      <footer>
        <div>Footer</div>
      </footer>
    </>
  )
}

export default Layout
