name: CI
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      JSON_PLACEHOLDER_API: ${{ secrets.JSON_PLACEHOLDER_API }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: install pnpm
        run: npm install -g pnpm

      - name: install
        run: pnpm install

      - name: build
        run: pnpm build
